#!/usr/bin/env python
ACCOMPLICE = 'ACCOMPLICE'
ADJUST_COMPETENCE = 'ADJUST_COMPETENCE'
ALSO = 'ALSO'
ATTEMPT = 'ATTEMPT'
BONUS = 'BONUS'
CASUAL = 'CASUAL'
COMMENT_MARKER = '#'
DATE = 'DATE'
DATE_FORMAT = 'dd.mm.yy'
EVENT = 'EVENT'
KILLS = 'KILLS'
LONG_GAME = 'long'
NAME = 'NAME'
NAME_MARKER = '"'
PLAYER_OP = 'PLAYER_OP'
POLICE_NEW = 'POLICE_NEW'
POLICE_RERANK = 'POLICE_RERANK'
POLICE_RES = 'POLICE_RES'
REDEEMED = 'REDEEMED'
REMOVE = 'REMOVE'
SHORT_GAME = 'short'
TIME = 'TIME'
TIME_FORMAT = 'hh:mm'
WANTED = 'WANTED'
OPTION_OP_LIST = [BONUS, POLICE_RERANK, ADJUST_COMPETENCE]
PLAYER_OP_LIST = [REMOVE, CASUAL, WANTED, REDEEMED, ATTEMPT, ACCOMPLICE, EVENT, POLICE_NEW, POLICE_RES]
SCORES_PREAMBLE = '<?xml version="1.0" encoding="utf-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">  <head>     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>    <link rel="stylesheet" type="text/css" href="http://www.srcf.ucam.org/assassins/assassins.css"/>     <link rel="shortcut icon" href="http://www.srcf.ucam.org/assassins/assassins-favicon.png"/>     <title>The Assassins\' Guild - List of Players</title>   </head>   <body><hr/><h1><img class="dagger" src="http://www.srcf.ucam.org/assassins/img/cloak2.gif" alt="Cloak &amp; Dagger"/>       The Assassins\' Guild - List of Players</h1><hr/> <p xmlns="">'

SCORES_POSTAMBLE = '<hr/><p class="center">       | <a href="/assassins/">Home</a> || <a href="mailto:assassins@srcf.ucam.org">Email</a> |       <br/>| <a xmlns="" href="news.html">News</a> <!--a xmlns="" href="hups.html">Updates</a--> <!--a xmlns="" href="head.html">Headlines</a--> <!--a xmlns="" href="ScoresName.html">ScoresName</a--> <!--<a xmlns="" href="ScoresCollege.html">ScoresCollege</a>--> |<br/><a href="http://validator.w3.org/check/referer"><img src="http://www.srcf.ucam.org/assassins/img/valid-xhtml11.png" alt="Valid XHTML 1.1"/></a></p><hr/></body> </html>'
NEWS_PREAMBLE = '<?xml version="1.0" encoding="utf-8"?> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">  <head>    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>  <link rel="stylesheet" type="text/css" href="http://www.srcf.ucam.org/assassins/assassins.css"/>  <link rel="shortcut icon" href="http://www.srcf.ucam.org/assassins/assassins-favicon.png"/> <title>The Assassins\' Guild - May Week News</title> </head> <body><hr/><h1><img class="dagger" src="http://www.srcf.ucam.org/assassins/img/cloak2.gif" alt="Cloak &amp; Dagger"/>   The Assassins\' Guild - May Week News</h1><hr/>'
NEWS_POSTAMBLE = '  <hr/><p class="center">  | <a href="/assassins/">Home</a> || <a href="mailto:assassins@srcf.ucam.org">Email</a> |   <br/><a href="http://validator.w3.org/check/referer"><img src="http://www.srcf.ucam.org/assassins/img/valid-xhtml11.png" alt="Valid XHTML 1.1"/></a></p><hr/></body></html>'
